### ISSUE TITLE
Crash when vmOS is None

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-baseline-builder#52]
https://github.com/rapid7/vm-automation/issues/21

```
Traceback (most recent call last):
  File "build_linux_baselines.py", line 139, in <module>
    main(sys.argv)
  File "build_linux_baselines.py", line 132, in main
    build_base(target, common_vars, packer_file, replace_existing=replace_vms, vmServer=vm_server, prependString=prependString)
  File "build_linux_baselines.py", line 66, in build_base
    vm = vmServer.get_vm(prependString + vm_name)
  File "/r7-source/metasploit-baseline-builder/lib/serverHelper.py", line 32, in get_vm
    return vm_server.getVmByName(vm_name)
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/vm_automation/esxiVm.py", line 205, in getVmByName
    self.enumerateVms()
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/vm_automation/esxiVm.py", line 194, in enumerateVms
    self.vmList.append(esxiVm(self, i))
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/vm_automation/esxiVm.py", line 491, in __init__
    if '64-bit' in self.vmOS:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jmartin-r7** [comment]
Fixed by update to vm-automation library see https://github.com/rapid7/vm-automation/pull/20
