### ISSUE TITLE
Crash when API Snapshot not available

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-baseline-builder#53]
```
Traceback (most recent call last):
  File "build_linux_baselines.py", line 139, in <module>
    main(sys.argv)
  File "build_linux_baselines.py", line 132, in main
    build_base(target, common_vars, packer_file, replace_existing=replace_vms, vmServer=vm_server, prependString=prependString)
  File "build_linux_baselines.py", line 83, in build_base
    vm.takeSnapshot(snapshotName='baseline')
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/vm_automation/esxiVm.py", line 893, in takeSnapshot
    setQuiescent)
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/var/jenkins_home/.pyenv/versions/2.7.13/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.RestrictedVersion: (vim.fault.RestrictedVersion) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Current license or ESXi version prohibits execution of the requested operation.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

**Comment by jmartin-r7** [comment]
Fixed by update to vm-automation library see https://github.com/rapid7/vm-automation/pull/22

Snapshots are now silently skipped.  Leaving this open for the time being while considering adding a summary report and details about when snapshots are not taken.
