### ISSUE TITLE
Unhandled exception while running baseline builder

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-baseline-builder#6]
I had an unhandled exception while running the builder.  It caused:
```
builder@ubuntu:~/rapid7/metasploit-baseline-builder$ python build_baselines.py
 65%|█████████████████████████████████████▏                   | 15/23 [12:31:40<6:40:53, 3006.70s/it]Traceback (most recent call last):
  File "build_baselines.py", line 315, in <module>
    main(sys.argv)
  File "build_baselines.py", line 302, in main
    build_base(file_name, iso_map[file_name], replace_vms)
  File "build_baselines.py", line 248, in build_base
    p.build(parallel=True, debug=False, force=False)
  File "/usr/local/lib/python2.7/dist-packages/packer.py", line 63, in build
    return self.packer_cmd()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 486, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/usr/bin/packer build -parallel=true -only=vmware-iso -var vm_name=Win10x64_1511 -var iso_url=./iso/en_windows_10_multiple_editions_version_1511_updated_apr_2016_x64_dvd_8705583.iso -var autounattend=./tmp/Win10x64_1511/Autounattend.xml -var esxi_datastore=SSD_VMs -var esxi_host=REDACTED -var vagrantfile_template=vagrantfile-windows_packer.template -var guest_os_type=windows9-64 -var esxi_cache_datastore=SSD_OS -var esxi_username=REDACTED -var iso_checksum_type=md5 -var esxi_network=PAYLOAD_TEST -var output=./box/windows_10_x64_1511_vmware.box -var iso_checksum=3ca03a2c59ae5b58ca965a345d4f2ae1 -var esxi_password=REDACTED ./tmp/Win10x64_1511/current_packer.json'

  STDOUT:


  STDERR:
```

I did get most of the VMs built.  The catch was that neither of the 2008 servers that got built had python.  Not sure if that's an artifact from the error or what.  I'm going to try to rebuild tonight.

**Comment by bwatters-r7** [comment]
The script ran the second time perfectly.  I guess there were grimlins somewhere.

**Comment by jmartin-r7** [comment]
This exception is a VM failing, we can add a catch for this specific error and print a more pretty failure message.

The 2008 servers missing python prolly needs a separate issue.
